### PR TITLE
Proximity bug fix

### LINKED ISSUE #24: Fix canvas error on proximity object over an object without custom data property

### PR DESCRIPTION
**Pull request by aslamcodes**
closes #24

### CODE REVIEW

**Comment by aslamcodes** [comment]
Okayish

File: src/components/Slide/CanvasHandler.ts [hunk 1]
```diff
@@ -93,16 +95,17 @@ export class CanvasHandler {
...
+        if (!(element as FabricObject).customData) return;
+
+        if (isEqual(element, group)) return;
+
+        if (!areObjectsNear(element, group)) return;
+
+        text.set("text", (element as FabricObject).customData);
+
+        setTimeout(() => {
+          text.set("text", "");
```
Comment (jayvanandel07) [inline src/components/Slide/CanvasHandler.ts:107]: why use settimeout?

**Review by jayvanandel07 — APPROVED** [review]

File: src/components/Slide/CanvasHandler.ts (hunk 1 above)
Comment (aslamcodes) [reply src/components/Slide/CanvasHandler.ts:107]: I felt like having the sensed data from the proximity sensor is better removed
